### PR TITLE
Rebase on mono/mono-addins main branch

### PR DESCRIPTION
**Pull request by Molytho**
They did a partial swap to .net standard 2.0 in the main repo so this is probably the most easy way to get .net standard into this.
This breaks DotDevelop build but the error can be fixed by updating System.Collections.Immutable to version 6.0.0 in MonoDevelop.AspNetCore so this should not be an issue

### CODE REVIEW

**Comment by hwthomas** [comment]
@Molytho This is really useful work!  It's always a problem to keep up with ongoing developments in submodules, and from what I've seen recently ([Issue 205](https://github.com/mono/mono-addins/issues/205), [206](https://github.com/mono/mono-addins/issues/206)), it looks as if mono-addins should (soon) work with net6/netstandard2.0.  These issues are still being worked on, so it may be worth waiting to see how they get resolved before updating the `dotdevelop/mono-addins` fork.  However, you have checked that it's straightforward to fix the dotdevelop build once `mono-addins` have been updated, which is great.

I'm also wondering if, instead of rebasing the 3 commits that @lytico has added to the current detached HEAD (@7ac9608) it may be more transparent to change the commit used for the submodule to that of the latest [mono/mono-addins](https://github.com/mono/mono-addins) one, and then create a branch (eg dotdevelop) just for these 3 commits.  That would save adding the 156 commits from the mono repo to the forked one, which would now have just the 3 new ones.  It still means that the fork has to be updated in synchronism with a dotdevelop PR, but the history should be more obvious, I think 

wdyt?

**Comment by hwthomas** [comment]
@Molytho  The [issue](https://github.com/mono/mono-addins/issues/205) that I mentioned above has now been resolved, so it would be good to update your PR to that latest [commit](https://github.com/mono/mono-addins/commit/ecf7a974d56af4c26009a191f6a9182f88b12623) and get it merged.   

Thinking again about my last comment, which I initially thought might seem to be a clearer approach,  I'm now thinking that this would be re-writing the commit history, and although it might effectively end up at the same point, would not be an 'approved' thing to do!  I don't have a lot of experience in this area, so I'm happy to be advised by you.  

It will still be necessary to coordinate the update of this submodule with changing `System.Collections.Immutable to version 6.0.0 in MonoDevelop.AspNetCore` that you mention.  Are you able to try out the combination of the 2 changes in advance, somehow?  Again, I'd be grateful for any advice on getting this right!

**Comment by Molytho** [comment]
Update is done and tested. Still builds and works fine after the update in AspNetCore.

**Comment by vanackerglenn** [comment]
I don't think there would be an issue merging this, it's mostly a rebase on the original branch, which was released. As for the 3 added commits, it looks like they are going in the right direction.
I would advise to also create a develop branch on this repo, so the main dotdevelop dev branch could use the develop branches of it's submodules to test things before everything is released. Ideally, I would even opt to have those submodules be references via nuget packages, because that makes it easier to select a distinct version.
But for the time being, I would merge this. great work @Molytho!

**Comment by hwthomas** [comment]
@gluckez Would you base the `develop` branch at the current detached HEAD position - `@7ac96087d7` - where the `dotdevelop_gtksharp` branch is based (fortunately there is no `develop` branch in the [upstream](https://github.com/mono/mono-addins)  repo)?

**Comment by vanackerglenn** [comment]
@hwthomas I would base it on master, after this pr is merged. or maybe even better, use this repo as a testing branch before requesting a merge upstream. it seems like that one is still being maintained anyway, so why not use it instead of having our own version. but that's just my opinion.

**Comment by hwthomas** [comment]
@gluckez  I'll merge this PR, and then create a `develop` branch in this fork of `mono-addins`.  

Should updating  `System.Collections.Immutable` to version 6.0.0 in `MonoDevelop.AspNetCore.csproj`  need a separate PR in the dotdevelop repo, or could this just be a "Fix Build" commit in the code?

**Comment by hwthomas** [comment]
@Molytho : this is now merged, but a fresh clone of dotdevelop builds fine (on Ubuntu 20.04) without needing to update `System.Collections.Immutable` to Version 6.0.0 as you advise.   

Any comments before I close this PR?

**Comment by Molytho** [comment]
I think this is because the submodule in dotdevelop still references the old commit. We have to update it with "git submodule update --remote main/external/mono-addins" followed by a commit. I will open an according PR later.

**Comment by hwthomas** [comment]
@Molytho : Yes, I think that's it.  I'm away until the weekend, but will try again then.

**Comment by hwthomas** [comment]
@Molytho : I'd done the  `git submodule update --remote main/external/mono-addins` bit, but forgot the commit afterwards, so my 'fresh clone' was using the old submodule content.  Thanks for pointing this out so clearly! - and thanks for doing the PR in dotdevelop as well  I'll close this PR now.

**Pull request merged**
