### PR TITLE
port projects to net standard and add build.yml

### PR DESCRIPTION
**Pull request by vanackerglenn**
creating a pr here as proposed by @knocte here: https://github.com/dotdevelop/dotdevelop/pull/91#issuecomment-1295743208
I have no experience porting to SDK style projects and porting from .net framework to .net standard, so feel free to review and correct me, but I feel changes like this are useful in the long term.

### CODE REVIEW

**Comment by Molytho** [comment]
It will not be that easy. Your build.yml doesn't build Mono.Addins.GuiGtk3. Building it fails with many errors coming from .net framework libraries referenced. Making this build requires replacing all these dependencies but this is impossible without using gtk3 as far as I'm aware of (I didn't find gtk-sharp-2 with .netstandard target).
I guess we need to migrate to gtk3 for dotdevelop if we want to get it working

**Comment by vanackerglenn** [comment]
ugh, you're right :( I managed to get Gtk3 addins working locally, but gtk2 fails, and dotdevelop is mostly still built on that. And even in the Gtk3 implementation we're targetting obsolete api's. I guess a Gtk upgrade is absolutely needed on our roadmap if we ever want to target netstandard.

**Comment by hwthomas** [comment]
@gluckez I'm adding this comment here (rather than in the `dotdevelop PR#91` discussion) because continuing it there seems out of context.  

I'm supportive of your idea of converting self-contained parts of `dotdevelop` to netstandard2.0 "little-by-little", where that's possible.  Like you, I don't have experience of doing this, and @molytho 's comment shows that it may be more complex than first thought!  

It took me some time to track down this PR, so would it be worth adding a reference to it in the `dotdevelop PR#91` discussion?  

Edit: Oh, I see you have done! But perhaps leaving this PR Open, marked with a DO NOT MERGE warning?  

We also need a proper plan for migrating to gtk3.

**Comment by Molytho** [comment]
Actually there might be a way to switch to .net standard. Apparently there is a compatibility mode which allows using .net framework dependencies (https://learn.microsoft.com/en-us/dotnet/core/porting/third-party-deps).
In the main repo they did a partial switch to .net standard so through a rebase we can get this. I opened a PR for this (#2)

**Comment by vanackerglenn** [comment]
@Molytho That does seem like an interesting approach, I'll see if I can find the time to build it locally with those changes.
@hwthomas indeed, I was thinking of going back to that pr and continuing the discussion there, but like you said, we need a proper plan for migrating to gtk3. I don't think the discussion on your pr is the place to make that plan though. I think we should have a dedicated thread, and all agree on the roadmap for future releases, after your pr's have been merged. 
For starters, like yourself, I think we need a dedicated develop branch as the main branch on these repo's, so we can continue working without potentially breaking anything on the master build. Then, when we choose to release, we can do so easily by just merging develop into master.
But I really closed this pr, so we don't get sidetracked too much from our objectives now and start merging things we haven't fully agreed on yet.

**Comment by Molytho** [comment]
@gluckez
https://github.com/Molytho/mono-addins/tree/netstandard
This is as far as I have gotten. Mono.Addins.GuiGtk3 builds fine without mono and dotdevelop still builds.
I am quiet sure that Mono.Addins.Gui can't be migrated to netstandard because the only available gtk2 nuget packages mono.posix which breaks dotdevelop build.

**Pull request closed without merging**
